### PR TITLE
Create icon request template

### PR DESCRIPTION
**Pull request by germain-gg**

### CODE REVIEW

**Comment by janogarcia** [comment]
@gsouquet I'd suggest consolidating it into two sections:

- Context — Briefly describe the concepts you need to represent and where it’s going to be used
- Reference examples — Material Symbols icon name, link to Figma if you are creating the icon from scratch, or any other reference

**Comment by janogarcia** [comment]
@gsouquet Also, I couldn't figure out if your issue template can be previewed, so I'm unsure how the helper text will be rendered. Should we use a template [similar to that of Element Web](https://github.com/vector-im/element-web/blob/develop/.github/ISSUE_TEMPLATE/bug-web.yml) so that we can keep the helper text visible?

**Review by janogarcia — COMMENTED** [review]
99.9% of the time I forget to submit my comments via the review form. Please find them above.

**Comment by kerryarchibald** [comment]
Didn't notice this before https://github.com/vector-im/compound/commit/806f9d6d90b58c349ae3bc13efabc1898f61b9f1

**Pull request closed without merging**
